### Linear Algebra

#### Objectives
* Use operations with vectors and matrices to solve systems of linear equations
  * Identify and describe of scalars, vectors,  matrices, using appropriate mathematical jargon
  * Create each linear algebra structure with numpy
  * Perform operations with vectors and matrices with numpy
    * multiplication, addition
    * dot product
    * transpose
    * inverse matrices
  * Visually represent each one of these equations 
  * Set up and solve systems of linear equations with real life examples


## Why Linear Algebra?

Linear Algebra is the basis of many machine learning models.

Data is usually already set up into a matrix by default!

<img src= "./resources/dataset.jpeg">

It can be used to model complicated things like language

<img src = "./resources/Word-Vectors.png">

Important for image compression and recognition

<img src = "./resources/images.gif">

Recommendation engines are able to make much more sophisticated recommendations by using linear algebra in conjunction with user and content data.

<img src = "./resources/netflix.png">

In [ ]:
import numpy as np

## Vectors

An array with magnitude and direction. The coordinates of a vector represent where the tip of the vector would be if you travelled from the origin.


Operations with vectores
Assume

$ \vec{v} = \begin{bmatrix}v_{1} \\v_{2}\end{bmatrix} $


$ \vec{w} = \begin{bmatrix}w_{1} \\w_{2}\end{bmatrix} $

$ \vec{v} + \vec{w} = \begin{bmatrix}v_{1} + w_{1} \\v_{2} + w_{2}\end{bmatrix} $

What is happening graphically? Let's look at an example:


In [88]:

import numpy as np
v = np.array([2, 4])
w = np.array([3, 2])
v + w

array([5, 6])

## Scalars

Have magnitude only. Can be multiplied by a vector or matrix to create a change in **scale** and/or direction.

What scalars would you need to change the direction of a vector?

In [17]:
v * 4

array([ 8, 16, 20])

### Linear Combination
If $v_{1},...,v_{n}$ are vectors and $a_{1},...,a_{n}$ are scalars, then the linear combination of those vectors with those scalars as coefficients is

<img src = "./resources/linear_combinations.svg"> 

### Dot Product

Can be thought of as one vector projected onto another

The dot product of v and w is $v \cdot w = (v_{1})(w_{2}) + (v_{1})(v_{2}) $


If v and w are perpendicular ($90^\circ$), their dot product will be 0.

If the angle between v and w is < $90^\circ$, the dot product will be positive.

If the angle between v and w is between $90^\circ$ and $180^\circ$, the dot product will be negative.





“The scalar projection of A onto B multiplied by the magnitude of B”

“The scalar projection of B onto A multiplied by the magnitude of A”

<img src = "./resources/dot_product.png">

<img src = "./resources/dot_product_components.png">

We are essentially, rotating vectors to the point of 
a · b = |a| × |b| × cos(θ)

Analogy from https://www.youtube.com/watch?v=FrDAU2N0FEg

In [43]:
v.dot(w)

-28

### Application of dot product:

Imagine you are an e-commerce company. You have vectors to represent the transactions made with one of your items. Q is the quantity and represent the amount of cash either bought or sold.

$ Income = (q_{1},q_{2},q_{3})\cdot (p_{1},p_{2},p_{3}) $

What story is this telling?

In [44]:
q = np.array([4,6,10])
p = np.array([50,-30,45])

q.dot(p)

470

### Magnitude of a vector




$length = \|v \| = \sqrt{v \cdot v} = (v_{1}^2 + v_{2}^2 + \cdot \cdot \cdot \cdot + v_{n}^2)$


In [86]:
np.linalg.norm(q)

12.328828005937952

## Matrices

An m x n matrix will have m rows and n columns.

Question: In the context of machine learning which defines the number of features you have? What defines the number of observations you have?

Let's create the matrix 

$\begin{pmatrix}2 & 4 \\6 & 8 \\ 10 & 12\end{pmatrix}$ 

What would we call this matrix?

In [24]:
A = np.array([[2, 4], [6, 8], [10, 12]])

print(A)
print('shape of A:',A.shape)

[[ 2  4]
 [ 6  8]
 [10 12]]
shape of A: (3, 2)


Taking the **transpose** of a matrix will flip the rows and columns. You fill find this an important step when performing operations with numpy.

In [27]:
transpose_a = A.T
print(transpose_a)

[[ 2  6 10]
 [ 4  8 12]]


### Multiplying Matrices

Why does order matter, an intuitive approach?
The associative/commutative properties do not hold for matrices!

i.e. 

$AB ≠ BA $  

and

$(AB)C ≠ A(BC)$


We can geometrically think of a matrix as performing a transformation.

The *columns* of your first matrix must match the *rows* of your second. 

When multiplying two matrices: 

$ m_{1} \ x \  n_{1} $ matrix by a 

$ m_{2}\ x \ n_{2} $ matrix

The resultant matrix will be $m_{1} \ x \ n_{2}$

In [56]:
a

b = np.array([[5,20],[10,4]])

print('a.b \n', a.dot(b))
print('---------')
print('b.a \n',b.dot(a))

a.b 
 [[-15  12]
 [ 35  68]]
---------
b.a 
 [[ 65  30]
 [ 22 -12]]


## Inverse of Matrices

It is not possible to divide by matrices. What we can do is find the **inverse** of a matrix. When a matrix is multiplied by its inverse, it results in the identity matrix. When a matrix is multiplied by an identity matrix, it will result in the same matrix (think of it as the operational equivalent to 1 for linear algebra).

<img src = "./resources/inverse.webp">

An identity matrix will be square with a diagonal of 1's moving from left to right and the remaining numbers 0.

<img src = "./resources/identity_matrix.svg">

The order of multiplication does not matter for a matrix and its inverse:

$A \cdot A^{-1} = A^{-1} \cdot A $



In [32]:
x = np.array([[4,8,10],[3,9,12],[5,10,15]])
i_3 = np.identity(3)

In [35]:
x

array([[ 4,  8, 10],
       [ 3,  9, 12],
       [ 5, 10, 15]])

In [36]:
x.dot(i_3)

array([[ 4.,  8., 10.],
       [ 3.,  9., 12.],
       [ 5., 10., 15.]])

In [80]:
inv_x = np.linalg.inv(x)
inv_x

array([[ 5.00000000e-01, -6.66666667e-01,  2.00000000e-01],
       [ 5.00000000e-01,  3.33333333e-01, -6.00000000e-01],
       [-5.00000000e-01, -7.40148683e-17,  4.00000000e-01]])

In [84]:
np.round(x.dot(inv_x))

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [-0., -0.,  1.]])

In [83]:
np.round(inv_x.dot(x))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

## Systems of Equations

You are freelancing as a data scientist, and things are going great! You have just completed two jobs, however, you cannot remember the rate you set for each one.

Let's assume we have two equations:


`` x - 2y = 1 ``

`` 3x + 2y = 11`` 

Let's try and solve it 

1. with a system of equations
2. graphically

How could we formulaically solve for our vector x? We can't divide by A!!! We can, however, multiply by the inverse to both sides

$ A \cdot X = B $

$ A^{-1} A X = A^{-1} \cdot B  $

$I \cdot X   = A^{-1} \cdot B $

$\begin{pmatrix}1 & -2 \\3 & 2 \end{pmatrix} \cdot \begin{pmatrix}x \\ y \end{pmatrix} = \begin{pmatrix}1 \\11\end{pmatrix}$ 

In [74]:
a = np.array([[1,-2],[3,2]])
b = np.array([[1],[11]])
inv_a = np.linalg.inv(a)


inv_a.dot(b)

array([[3.],
       [1.]])

In [75]:
inv_a.shape

(2, 2)

In [65]:
inv_a.dot(b)

array([[3.],
       [1.]])

More resources: 

### 3 Blue 1 Brown:  https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_a

So good!!!!