## Up Next:

Linear Regression with Linear Algebra



In [144]:
import pandas as pd
car_df = pd.read_csv('http://www-bcf.usc.edu/~gareth/ISL/Auto.csv',na_values='?').dropna()
car_df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0       130.0    3504          12.0    70   
1  15.0          8         350.0       165.0    3693          11.5    70   
2  18.0          8         318.0       150.0    3436          11.0    70   
3  16.0          8         304.0       150.0    3433          12.0    70   
4  17.0          8         302.0       140.0    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [145]:
X_df = car_df[['cylinders','displacement','horsepower','weight','acceleration','year']]
y= car_df['mpg']


In [146]:
X_df.head()

cylinders  displacement  horsepower  weight  acceleration  year
0          8         307.0       130.0    3504          12.0    70
1          8         350.0       165.0    3693          11.5    70
2          8         318.0       150.0    3436          11.0    70
3          8         304.0       150.0    3433          12.0    70
4          8         302.0       140.0    3449          10.5    70

In [147]:
X_df['constant'] = 1

/Users/forest.polchow/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [148]:
y.head()

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

Our linear regression equation can be represented as:

$ y = Xb + error $

to begin with, we are going to assume that on average, the error is equal to 0. (We can assume this due our assumptions for linear algebra)



$ y = Xb  + 0 $   --> $ y = Xb $

We want to solve for b. That means we need to isolate it on one side of the equation therefore we can take the inverse of this function. Let's multily by the inverse. Let's calculate it:

$ X^{-1} $


In [149]:
x = X.values

In [150]:
np.linalg.inv(x)

LinAlgError: Last 2 dimensions of the array must be square

We can only calculate an inverse of a **square** matrix. We can make accomplish this be multiplying the matrix by its transpose.

$X^{T} y = X^{T} X b $

Now we can take the inverse of the new square matrix $X^{T}X$ and multiply it to both sides to isolate with b vector

$ (X^{T}X)^{-1} X^{T}y = (X^{T}X)^{-1} (X^{T}X)b$ 

$(X^{T}X)^{-1}X^{T}y = I b$

We are left with the identity matrix multiplied by b, which is simply equal to b

$b = (X^{T}X)^{-1}X^{T}y  $

Now, solve for b!

In [151]:
## this makes the matrix
x_transposed = x.T

In [152]:
x_transposed.shape

(7, 392)

In [155]:
Xt_X = x_transposed.dot(x)

In [156]:
Xt_X.shape

(7, 7)

In [157]:
XtX_inv = np.linalg.inv(Xt_X)
Xty = x_transposed.dot(y)
x_hat = XtX_inv.dot(Xty) 
x_hat

array([-3.29859089e-01,  7.67843024e-03, -3.91355574e-04, -6.79461791e-03,
        8.52732469e-02,  7.53367180e-01, -1.45352505e+01])

In [158]:
len(x_hat)

7

In [166]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

skl_X = X_df.drop(columns = 'constant')

In [167]:
lr.fit(skl_X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [169]:
lr.intercept_

-14.53525048050609

In [170]:
lr.coef_

array([-3.29859089e-01,  7.67843024e-03, -3.91355574e-04, -6.79461791e-03,
        8.52732469e-02,  7.53367180e-01])

In [74]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.((a,b))


array([1, 2, 3, 2, 3, 4])

In [65]:
new_matrix.shape

(2779,)

In [49]:
x_transposed.dot(matrix_x)

array([[1.29750000e+04, 4.86267000e+05,            nan, 6.94905800e+06,
        3.27751000e+04, 1.63819000e+05],
       [4.86267000e+05, 1.91840632e+07,            nan, 2.60915663e+08,
        1.13332640e+06, 5.78247900e+06],
       [           nan,            nan,            nan,            nan,
                   nan,            nan],
       [6.94905800e+06, 2.60915663e+08,            nan, 3.78721588e+09,
        1.79557956e+07, 8.92313170e+07],
       [3.27751000e+04, 1.13332640e+06,            nan, 1.79557956e+07,
        9.90603200e+04, 4.70451300e+05],
       [1.63819000e+05, 5.78247900e+06,            nan, 8.92313170e+07,
        4.70451300e+05, 2.29816000e+06]])

In [17]:
X.shape

(397, 6)


The linear regression is computed as $(X^{T}X)^{-1} X^{T}Y $

If X is an (n x k) matrix:

$ (X^{T} X) $ takes $ O(n*k{^2})$ time and produces a (k x k) matrix

The matrix inversion of a (k x k) matrix takes $ O(k^{3}) $ time

$(X^{T}Y)$ takes $O(n*k^{2})$ time and produces a (k x k) matrix

The final matrix multiplication of two (k x k) matrices takes $ O(k^{3}) $ time


Long story short, it can take a looooong time!

More on O(n) notation here: https://en.wikipedia.org/wiki/Computational_complexity_of_mathematical_operations#Matrix_algebra

### The solution

Gradient Descent! (You'll learn about this tomorrow)

<img src = "./resources/gradient_descen6.png">

Closed Form v. Gradient Descent with regression
https://stats.stackexchange.com/questions/23128/solving-for-regression-parameters-in-closed-form-vs-gradient-descent

Deriving the formula for least square estimation
https://web.williams.edu/Mathematics/sjmiller/public_html/BrownClasses/54/handouts/MethodLeastSquares.pdf